# Generated by Django 5.2.4 on 2025-07-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="titel",
            new_name="title",
        ),
    ]
