name: Django CI

on:
  push:
    branches: [ "main" ,"dev"]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.13.3 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "SECRET_KEY=dummy" >> .env
        echo "DB_NAME=test_db" >> .env
        echo "DB_USER=root" >> .env
        echo "DB_PASSWORD=" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "TEST=True" >> .env

    - name: Run Tests
      run: |
        python manage.py test
